runtime: python39  # Use Python 3.9 runtime

entrypoint: gunicorn -b :$PORT app:app  # Command to start the app

env_variables:
  FLASK_ENV: production

instance_class: F4_1G  # Provides 2 GB of memory

# Automatic scaling (optional)
automatic_scaling:
  target_cpu_utilization: 0.65
  max_instances: 3